CXX = g++
CFLAGS = -g -Wall
LINKING = -lglut -lGL -lGLU

SOURCES = tinyxml2.cpp test_xml.cpp \
          arena.cpp arena_obstacles.cpp player.cpp utils.cpp \
		  bullet.cpp arena_parser.cpp 
TARGET = test

all: $(TARGET)

# Compila todos os .cpp em um único executável
$(TARGET): $(SOURCES)
	$(CXX) $(CFLAGS) -o $@ $^ $(LINKING)

clean:
	rm -f $(TARGET)
